### ISSUE TITLE
panic on cycle of types (expected error without a panic)

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/verus#100]
I really don't know what's going on here... consider this code, which has a cycle of types, and should therefore be rejected:

```rust
#[allow(unused_imports)]
use builtin::*;

mod pervasive;
use pervasive::*;
use pervasive::modes::*;
use pervasive::option::*;
#[allow(unused_imports)]
use state_machines_macros::*;

pub struct X {
    pub t: X_Instance,
}

#[proof]
#[allow(non_camel_case_types)]
#[verifier(unforgeable)]
pub struct X_Instance {
    #[spec]
    state: X,
    #[spec]
    location: ::builtin::int,
}

impl X_Instance {
    #[proof]
    #[verifier(external_body)]
    #[verifier(returns(proof))]
    pub fn clone(#[proof] &self) -> Self {
        ensures(|s: Self| ::builtin::equal(*self, s));
        ::core::panicking::panic("not implemented");
    }
}
fn main() { }
```

Verus prints the following:

```rust
error[E0072]: recursive type `X` has infinite size
  --> o.rs:11:1
   |
11 | pub struct X {
   | ^^^^^^^^^^^^ recursive type has infinite size
12 |     pub t: X_Instance,
   |            ---------- recursive without indirection
   |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `X` representable
   |
12 |     pub t: Box<X_Instance>,
   |            ++++          +

error[E0072]: recursive type `X_Instance` has infinite size
  --> o.rs:18:1
   |
18 | pub struct X_Instance {
   | ^^^^^^^^^^^^^^^^^^^^^ recursive type has infinite size
19 |     #[spec]
20 |     state: X,
   |            - recursive without indirection
   |
help: insert some indirection (e.g., a `Box`, `Rc`, or `&`) to make `X_Instance` representable
   |
20 |     state: Box<X>,
   |            ++++ +

error[E0391]: cycle detected when computing drop-check constraints for `X_Instance`
  --> o.rs:18:1
   |
18 | pub struct X_Instance {
   | ^^^^^^^^^^^^^^^^^^^^^
   |
note: ...which requires computing drop-check constraints for `X`...
  --> o.rs:11:1
   |
11 | pub struct X {
   | ^^^^^^^^^^^^
   = note: ...which again requires computing drop-check constraints for `X_Instance`, completing the cycle
   = note: cycle used when computing dropck types for `Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing }, value: X_Instance } }`

error: aborting due to 3 previous errors; 3 warnings emitted

Some errors have detailed explanations: E0072, E0391.
For more information about an error, try `rustc --explain E0072`.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /Users/thance/verus/source/rust_verify/src/driver.rs:80:40
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /Users/thance/verus/rust/library/core/src/result.rs:1295:23
   4: rust_verify::driver::run
             at ./rust_verify/src/driver.rs:80:24
   5: rust_verify::main
             at ./rust_verify/src/main.rs:46:30
   6: core::ops::function::FnOnce::call_once
             at /Users/thance/verus/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The error messages look correct, but the Verus driver panics for some reason.

**Comment by Chris-Hawblitzel** [comment]
It's on this line: `let verifier = verifier.lock().unwrap();` from https://github.com/secure-foundations/verus/commit/ad92b2a8908a219ec84c277d2bb701934e9a8d9c
