### ISSUE TITLE
erasure bug

### ISSUE THREAD

**Issue by tjhance** [secure-foundations/verus#78]
```rust
#[allow(unused_imports)]
use builtin::*;
mod pervasive;
use pervasive::*;
use pervasive::modes::*;
use pervasive::option::*;

fn f<T>(t: Spec<Option<T>>) {
    #[spec] let x = t.value().get_Some_0();
}

fn main() {
}
```

gives this error:

```
thread 'rustc' panicked at 'internal error: MethodCall ResolvedCall', rust_verify/src/erase.rs:610:22
```

**Comment by matthias-brun** [comment]
I encountered a very similar (the same?) issue with `is_None`:

```rust
#[allow(unused_imports)]
use builtin::*;
mod pervasive;
#[allow(unused_imports)]
use pervasive::{*, option::Option};

fn f() -> bool {
    let x: Option<usize> = Option::None;
    x.is_None()
}

fn main() {
}
```

results in:

```
thread 'rustc' panicked at 'internal error: MethodCall ResolvedCall', rust_verify/src/erase.rs:610:22
```
